package de.lbakker77.retracker.main.domain;

public enum TaskCategory {
    GENERAL,
    ADMINISTRATIVE,
    PERSONAL,
    WORK_PROFESSIONAL,
    FINANCIAL,
    HEALTH_WELLNESS,
    HOME_MAINTENANCE,
    SOCIAL_RELATIONSHIPS,
    EDUCATION_LEARNING,
    CREATIVE,
    TRAVEL_LOGISTICS,
    ERRANDS_SHOPPING
}
